name: LastOnline
version: ${project.version}
api-version: "1.16"
main: net.lapismc.lastonline.LastOnline
authors: [Dart2112]
description: Shows a list of the last players online with times
permissions:
  lastonline.use:
    description: "Allows players to see the last players to be online"
    default: op